- name: Deploy logrotate configs for Redis & Sentinel
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { name: "redis",  src: "redis.logrotate.j2",  dest: "/etc/logrotate.d/redis" }
    - { name: "sentinel", src: "redis-sentinel.logrotate.j2", dest: "/etc/logrotate.d/redis-sentinel" }
  when: >
    item.name != 'sentinel'
    or (groups['redis'] is defined and inventory_hostname in groups['redis'])
