- name: Deploy logrotate config for Redis
  ansible.builtin.template:
    src: redis.logrotate.j2
    dest: /etc/logrotate.d/redis
    owner: root
    group: root
    mode: '0644'

- name: Deploy logrotate config for Redis Sentinel
  ansible.builtin.template:
    src: redis-sentinel.logrotate.j2
    dest: /etc/logrotate.d/redis-sentinel
    owner: root
    group: root
    mode: '0644'
  when: redis_replication | bool
