# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Include base OS updates
  ansible.builtin.include_role:
    name: os

- name: Install yum-config-manager
  ansible.builtin.yum:
    name: yum-utils
    state: present
    update_cache: true

- name: Add Hashicorp Vault repo
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp Vault repo
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    state: present
    gpgcheck: false

- name: Install vault
  ansible.builtin.yum:
    name: "{{ vault_version }}"
    update_cache: true
    state: present

- name: Create vault group
  ansible.builtin.group:
    name: "{{ vault_group }}"
    state: present

- name: Create vault user
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    state: present

- name: Ensure the directories for the vault data exists
  ansible.builtin.file:
    path: "{{ vault_dir }}/data"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0770"

# Check if firewalld is running, if it is then open the appropriate ports
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Open Vault Ports on FirewallD Public Zone
  ansible.posix.firewalld:
    port: "{{ vault_port }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  with_items:
    - "{{ vault_port }}"
    - "{{ vault_cluster_port }}"
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"
    - ansible_facts.services["firewalld.service"].status == "enabled"

# Configure vault
- name: Create vault config file
  ansible.builtin.template:
    src: "config.hcl.j2"
    dest: "{{ vault_dir }}/config.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0640"

- name: Create service unit file
  ansible.builtin.template:
    src: "vault.service.j2"
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: "0644"

- name: Enable and start vault
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true
    daemon_reload: true
