# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Location of mongo conf file
mongo_conf_file: /etc/mongod.conf

# Key file destination location
# The key file is used to authenticate members of a replica set
mongo_auth_keyfile_destination: /etc/ssl/mongo-replicaset-key.pem

mongo_owner: mongod
mongo_group: mongod
