# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

iap_release: 2021.2

iap_textfsm_version:
  "7": 1.1.0
  "8": 1.1.2

iap_jinja2_version:
  "7": 2.11.3
  "8": 2.11.3

iap_nodejs:
  "7":
    version: 14
    url: https://rpm.nodesource.com/setup_14.x
  "8":
    version: 14

iap_python_version:
  "7": 3.9.5
  "8": 3.9.5
