# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

epel_location: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

os_packages:
  - chrony
  - coreutils
  - gcc
  - gcc-c++
  - make
  - openssl
  - yum-utils

security_packages:
  - audit
  - checkpolicy
  - iptables
  - libselinux
  - libselinux-utils
  - policycoreutils
  - policycoreutils-python-utils
  - selinux-policy
  - selinux-policy-mls
  - selinux-policy-targeted
  - setools-console

operational_packages:
  - bind-utils
  - curl
  - dos2unix
  - git
  - gzip
  - jq
  - man
  - rsyslog
  - sudo
  - sysstat
  - tar
  - tcpdump
  - telnet
  - unzip
  - wget
  - which
  - zip
