# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# The directory to install IAP in
iap_install_dir: /opt/itential

# The directory to write logs to
iap_log_dir: /var/log/itential

# The default user that runs the server process
iap_user: itential

# The default group that runs the server process
iap_group: itential

# Run IAP server as HTTPS
iap_https: false

# The IAP listen ports
iap_http_port: 3000
iap_https_port: 3443

# Should the platform role add necessary docs to mongodb? For a day
# zero install this would be true. However, a scenario where they
# already have a database but are using the Installer to do a
# blue/green style upgrade, would demand that they do NOT put
# any documents into their database. In that case, this var can
# be overridden and the mongo_init tasks will be skipped.
configure_iap: true

# Should the platform configure and add any IAG adapters that it
# discovers? Based on the presence of devices in the gateway group
# this will build adapter configs for each that it finds and insert
# them into the mongo database.
configure_iag_adapters: true

# Destination as referenced by itential user when connecting from itential host.
# This is ultimately stored in the mongo database to be read by IAP, therefore
# this is the location as seen from the IAP host.
itential_root_ca_file_destination: /opt/itential/keys/mongo-rootCA.pem
