# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

### RABBITMQ
- name: Install RabbitMQ
  hosts: rabbitmq, rabbitmq_secondary
  become: true
  roles:
    # Pull in the common vars
    - role: itential.deployer.common_vars
      tags:
        - always
  tasks:
    - name: Install RabbitMQ
      when: iap_release | float < 2023.2
      block:
        - name: Include base RabbitMQ role
          ansible.builtin.include_role:
            name: itential.deployer.rabbitmq
          tags:
            - rabbitmq
            - rabbitmq_install

        - name: Include RabbitMQ cluster role
          ansible.builtin.include_role:
            name: itential.deployer.rabbitmq_cluster
          when:
            - rabbitmq_cluster is defined
            - rabbitmq_cluster | bool
          tags:
            - rabbitmq
            - rabbitmq_cluster

        - name: Include RabbitMQ SSL role
          ansible.builtin.include_role:
            name: itential.deployer.rabbitmq_ssl
          when:
            - rabbitmq_ssl is defined
            - rabbitmq_ssl | bool
          tags:
            - rabbitmq
            - rabbitmq_ssl
