# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# Flag to remove the package-lock.json file before running the NPM install
delete_package_lock_file: false

# Flag to disable Git safe repo check
disable_git_safe_repo_checks: false

# Flag to prevent the NPM scripts from running when running the NPM install
npm_ignore_scripts: false
